name: 'Hello World'
description: 'Greet someone'
inputs:
  checkout-path:
    description: 'Path used in action/checkout'
    default: '.'
  ontology-file-path:
    description: 'Path to ontology file relative to repo base directory'
    required: true
  ontology-name:
    description: 'Name of ontology'
    required: true
  github-token:
    description: 'GitHub token'
    required: true
runs:
  using: "composite"
  steps:
    - name: Get ontology version
      run: ${{inputs.checkout-path}}/.github/workflows/get_version.sh ${{inputs.checkout-path}} ${{ inputs.ontology-file-path }}
      shell: bash
    - name: Build HTML for ${{ inputs.ontology-name }} - ${{ inputs.ontology-file-path }}
      if: success()
      run: |
           wget -O widoco.jar https://github.com/dgarijo/Widoco/releases/download/v1.4.17/java-11-widoco-1.4.17-jar-with-dependencies.jar
           mkdir -p publish/${{ inputs.ontology-name }}/v${{ env.ONTO_VERSION }}
           java -jar widoco.jar -ontFile ${{inputs.checkout-path}}/${{ inputs.ontology-file-path }} -outFolder publish/${{ inputs.ontology-name }}/v${{ env.ONTO_VERSION }} -htaccess -uniteSections -includeAnnotationProperties -lang en-de -getOntologyMetadata -noPlaceHolderText -rewriteAll -webVowl
           cp publish/${{ inputs.ontology-name }}/v${{ env.ONTO_VERSION }}/index-en.html publish/${{ inputs.ontology-name }}/v${{ env.ONTO_VERSION }}/index.html
      shell: bash
    - name: Publish to gh-pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v4
      with:
        target_branch: gh-pages
        build_dir: publish
        keep_history: true
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
    - name: Generate artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.ontology-name }}-${{ env.ONTO_VERSION }}
        path: publish
