name: 'Hello World'
description: 'Greet someone'
inputs:
  checkout-path:
    description: 'Path used in action/checkout'
    default: '.'
  ontology-file-path:
    description: 'Path to ontology file relative to repo base directory'
    required: true
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - run: ${{inputs.checkout-path}}/.github/workflows/get_version.sh ${{inputs.checkout-path}}/${{ inputs.ontology-file-path }}
      shell: bash
    - id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: echo "Ontology File Path ${{ inputs.ontology-file-path }}"
      shell: bash
    - run: echo "Ontology Version ${{ env.ONTO_VERSION }}"
      shell: bash
    - run: ${{inputs.checkout-path}}/goodbye.sh
      shell: bash
