on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
        with:
          path: checkoutpath
      - id: foo
        uses: MattTJung/action_onto_doc@develop
        with:
          path: checkoutpath
          ontology-file-path: './.github/workflows/testdata/ontology.ttl'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash