on: [push]

jobs:
  publish_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: MattTJung/action_onto_doc@develop
        with:
          ontology-file-path: './.github/workflows/testdata/ontology.ttl'
          ontology-name: 'ont_pub_tmplt'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: MattTJung/action_onto_doc@develop
        with:
          ontology-file-path: './.github/workflows/testdata/ontology2.ttl'
          ontology-name: 'ont_pub_tmplt2'
          github-token: ${{ secrets.GITHUB_TOKEN }}